#!/bin/bash
SPARK_HOME="/opt/spark"
SPARK_VERSION=spark-2.4.4

# Install jdk
apt-get install -y openjdk-8-jdk

# Install spark
cd /tmp
wget http://apache.cs.utah.edu/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop2.7.tgz
tar xvzf ${SPARK_VERSION}-bin-hadoop2.7.tgz
rm ${SPARK_VERSION}-bin-hadoop2.7.tgz
mkdir -p /opt
mv ${SPARK_VERSION}-bin-hadoop2.7 ${SPARK_HOME}

